import type { Metadata } from "next";
import "./globals.css";
import "primereact/resources/themes/bootstrap4-dark-blue/theme.css";
import TopNav from "@/components/TopNav";
import 'primeicons/primeicons.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
