import type { Metadata } from "next";
import TopNav from "@/components/TopNav";
import { getServerSession } from "next-auth"
import SessionProvider from "@/components/SessionProvider";

import "./globals.css";
import "primereact/resources/themes/bootstrap4-dark-blue/theme.css";
import 'primeicons/primeicons.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <TopNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
